Data binding tests
aartikov/Android-Architecture pull request #4
Opened 2020-09-24 14:52 UTC by Nemironium

Tests for binding packet

2020-09-24 15:27 UTC, aartikov requested changes

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/CommandTest.kt
> +    }
Самый главный кейс `receives command when started` не протестирован.
Можно переделать `receives command after starting` в него. А буферизация (не имеет значения одного элемента или нескольких) уже проверена в `saves commands before starting`

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +        println(testPropertyHost.state1)
`println` можно удалить

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +    }
`after two states changed` - значит, state1 ты тоже хотел менять?

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +class ComputedTest {
В других тестах мы пишем глаголы в третьем лице - returns, updates и т. д. Предлагаю тут сделать так же

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +}
Предлагаю все же добавить один тест, в котором за изменением computed наблюдают через bind. Мало ли, вдруг мы что-то упустили. Плюс, тесты можно рассматривать как справочную информацию о том, что умеет делать система, поэтому про bind будет не лишним упомянуть

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +        assertEquals(3, values.size)
тут тоже лучше все значение списка сравнивать

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +    fun `receives only last state after stopping`() {
`after stopping` 
`after restarted` не лучше отражает суть?

2020-09-24 15:27 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +    fun `receives nothing when destroyed`() = runBlockingTest {
может, лучше сделать `when stopped`? А то прочитав тесты можно не понять, что прием данных осуществляется в промежутке start-stop

2020-09-24 17:10 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +    fun `receives only last state after stopping`() {
Согласен, исправил

2020-09-24 17:10 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +    fun `receives nothing when destroyed`() = runBlockingTest {
Исправил

2020-09-24 17:11 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +        assertEquals(3, values.size)
Исправил

2020-09-24 17:13 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +class ComputedTest {
Упс... Исправил

2020-09-24 17:13 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +        println(testPropertyHost.state1)
Удалил)

2020-09-24 17:15 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +    }
Сделал аналогично, как в `updates computed value after three states changed`

2020-09-24 18:53 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +}
Добавил 2 теста с lifecycle

2020-09-24 19:17 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/CommandTest.kt
> +    }
Такое подойдёт?

2020-09-25 09:21 UTC, aartikov requested changes

2020-09-25 09:21 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +        propertyObserver.propertyObserverLifecycleOwner.onDestroy()
надо onStop?

2020-09-25 09:24 UTC, aartikov requested changes

2020-09-25 09:24 UTC, aartikov commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +        propertyObserver.propertyObserverLifecycleOwner.onDestroy()
надо onStop?

2020-09-25 09:33 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/StateTest.kt
> +        propertyObserver.propertyObserverLifecycleOwner.onDestroy()
Заменил

2020-09-25 09:33 UTC, Nemironium commented on lib/src/test/java/me/aartikov/lib/data_binding/ComputedTest.kt
> +        propertyObserver.propertyObserverLifecycleOwner.onDestroy()
Заменил

2020-09-25 09:38 UTC, merged